### ISSUE TITLE
error encountered while installing  'ifx_db

### ISSUE THREAD

**Issue by hongweijia** [ifxdb/node-ifx_db#1]
Dear all
Good day!
Firstly, I want to say it's great to see 'ifx_db' in NPM website. I have been looking for and waiting for it for so long a time. Thanks for your contribution! 
Secondly, I'm sorry to bother you that I encountered problems while installing the 'ifx_db' driver in my computer and so I'm writing to ask for your help!  

My computer environment for installing ifx_db is as follows.
OS: Linux (RedHat)
Node.js Version: v0.12.7
Informix (12.10 ) with CSDK installed.
node-gyp installed
gcc 5.2.0
nan 1.80

Erro log:

> ifx_db@1.0.0 install /Z/project/NodeStreaming/node_modules/ifx_db
> node installer/IfxDriverInstall.js

Using CSDK_HOME environment variable set to /opt/informix
make: Entering directory `/Z/project/NodeStreaming/node_modules/ifx_db/build'
  CXX(target) Release/obj.target/ifx_node_bind/src/odbc.o
make: Leaving directory`/Z/project/NodeStreaming/node_modules/ifx_db/build'

{ [Error: Command failed: /bin/sh -c node-gyp configure build --CSDK_HOME=$CSDK_HOME  --IS_DOWNLOADED=false
../src/odbc.cpp: In static function‘static v8::Localv8::Object ODBC::GetSQLError(SQLSMALLINT, SQLHANDLE, char_)’:
../src/odbc.cpp:935:17: error：can not convert the fourth parameter  in ‘SQLRETURN SQLGetDiagRec(SQLSMALLINT, SQLHANDLE, SQLSMALLINT, SQLCHAR_, SQLINTEGER_, SQLCHAR_, SQLSMALLINT, SQLSMALLINT_)’ from ‘SQLTCHAR_ {aka wchar_t_}’ to ‘SQLCHAR_ {aka unsigned char_}’
             &len);
                 ^
make: *_\* [Release/obj.target/ifx_node_bind/src/odbc.o] error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Z/application/node-v0.12.7-linux-x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Linux 2.6.18-164.el5
gyp ERR! command "node" "/Z/application/node-v0.12.7-linux-x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build" "--CSDK_HOME=/opt/informix" "--IS_DOWNLOADED=false"
gyp ERR! cwd /Z/project/NodeStreaming/node_modules/ifx_db
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
]

**Comment by msatyan** [comment]
The problem has been addressed with the current version  (v 1.0.1)
