### ISSUE TITLE
node-gyp build -v fails on ARM, include paths not generated by node-gyp configure -v

### ISSUE THREAD

**Issue by saraf** [ifxdb/node-ifx_db#13]
After running `node-gyp configure -v` and `node-gyp build -v` on a Raspberry Pi 2 with node 6.11.2 LTS
we get the following

> make: Entering directory '/home/pi/sandbox/node-ifx_db/build'
>   g++ '-DNODE_GYP_MODULE_NAME=ifx_node_bind' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DODBC64' '-DBUILDING_NODE_EXTENSION' -I/home/pi/.node-gyp/6.11.2/include/node -I/home/pi/.node-gyp/6.11.2/src -I/home/pi/.node-gyp/6.11.2/deps/uv/include -I/home/pi/.node-gyp/6.11.2/deps/v8/include -I../node_modules/nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF ./Release/.deps/Release/obj.target/ifx_node_bind/src/odbc.o.d.raw   -c -o Release/obj.target/ifx_node_bind/src/odbc.o ../src/odbc.cpp
> In file included from ../src/odbc.cpp:26:0:
> ../src/odbc.h:32:21: fatal error: infxcli.h: No such file or directory
>  #include <infxcli.h>
>                      ^
> compilation terminated.
> ifx_node_bind.target.mk:98: recipe for target 'Release/obj.target/ifx_node_bind/src/odbc.o' failed
> 

After running node-gyp configure -v the generated file build/ifx_node_bind.target.mk contains the following

> 
> INCS_Debug := \
>     -I/home/pi/.node-gyp/6.11.2/include/node \
>     -I/home/pi/.node-gyp/6.11.2/src \
>     -I/home/pi/.node-gyp/6.11.2/deps/uv/include \
>     -I/home/pi/.node-gyp/6.11.2/deps/v8/include \
>     -I$(srcdir)/node_modules/nan

Whereas, what is expected is:

> INCS_Debug := \
>   -I/home/pi/.node-gyp/6.11.2/include/node \
>   -I/home/pi/.node-gyp/6.11.2/src \
>   -I/home/pi/.node-gyp/6.11.2/deps/uv/include \
>   -I/home/pi/.node-gyp/6.11.2/deps/v8/include \
>   -I$(srcdir)/node_modules/nan \
>   **-I$(CSDK_HOME)/incl/cli**

**Comment by msatyan** [comment]
The infxcli.h is part of Informix Client SDK. (located at $(CSDK_HOME)/incl/cli)
The problem what you are seeing can happen due to either one of the reason. 
Please check whether you have installed CSDK; if not please install Informix Client SDK 4.10 xC2 or above (the latest is CSDK 4.10 xC9). 
If CSDK is already installed, then check whether the CSDK_HOME environment has set correctly.
Give a try and please let me know the feedback

**Comment by saraf** [comment]
Fixed by #14 
Thanks!
