### ISSUE TITLE
Ifx db in windows 

### ISSUE THREAD

**Issue by Ridan213** [ifxdb/node-ifx_db#5]
When execute query ,the node module allocates memory until the application crashes in windows 7 64 bits
any help is welcome
thanks in advance

**Comment by Ridan213** [comment]
Okay, I fixed the bug by rebuilding the module

**Comment by msatyan** [comment]
Glad to know you got the problem solved, 
If you could share the problem reproduction and the fix then I will integrate with the fix with the code line so that other will not hit the same problem.

**Comment by Ridan213** [comment]
@msatyan 
The problem is trying to use the module in windows environment without rebuilding.
Maybe in the documentation adding rebuild required as a step will make the using of module easier.
