### ISSUE TITLE
fatal error C1083: Cannot open include file: 'infxcli.h'

### ISSUE THREAD

**Issue by ecus** [ifxdb/node-ifx_db#7]
C:\wamp64\www\ecus2\node_modules\ifx_db>node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.0
gyp info using node@4.4.5 | win32 | x64
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Los proyectos de esta solución se van a compilar de uno en uno. Para habilitar l
a compilación en paralelo, agregue el modificador "/m".
  odbc.cpp
  odbc_connection.cpp
  odbc_statement.cpp
  odbc_result.cpp
**c:\wamp64\www\ecus2\node_modules\ifx_db\src\odbc.h(32): fatal error C1083: Cann
ot open include file: 'infxcli.h': No such file or directory (compiling source
file ..\src\odbc_statement.cpp) [C:\wamp64\www\ecus2\node_modules\ifx_db\build\
ifx_node_bind.vcxproj]
c:\wamp64\www\ecus2\node_modules\ifx_db\src\odbc.h(32): fatal error C1083: Cann
ot open include file: 'infxcli.h': No such file or directory (compiling source
file ..\src\odbc_connection.cpp) [C:\wamp64\www\ecus2\node_modules\ifx_db\build
\ifx_node_bind.vcxproj]
c:\wamp64\www\ecus2\node_modules\ifx_db\src\odbc.h(32): fatal error C1083: Cann
ot open include file: 'infxcli.h': No such file or directory (compiling source
file ..\src\odbc_result.cpp) [C:\wamp64\www\ecus2\node_modules\ifx_db\build\ifx
_node_bind.vcxproj]
c:\wamp64\www\ecus2\node_modules\ifx_db\src\odbc.h(32): fatal error C1083: Cann
ot open include file: 'infxcli.h': No such file or directory (compiling source
file ..\src\odbc.cpp) [C:\wamp64\www\ecus2\node_modules\ifx_db\build\ifx_node_b
ind.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Programador1\AppData\Roaming
\npm\node_modules\node-gyp\lib\build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:200:12)**
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Programador1\
\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build"
gyp ERR! cwd C:\wamp64\www\ecus2\node_modules\ifx_db
gyp ERR! node -v v4.4.5
gyp ERR! node-gyp -v v3.6.0
gyp ERR! not ok

C:\wamp64\www\ecus2\node_modules\ifx_db>

**Comment by msatyan** [comment]
Please check whether you have the right CSDK installed and the INCLUDE environment is set correctly. 
The location on the file is CSDKINSTALLDIR/incl/cli/infxcli.h
FYI: The build we have is 64Bit, (it should work for 32bit as well, though we have not tried)

**Comment by ecus** [comment]
I've installed IBM Informix Client SDK 3.70 (64-bit)

**Comment by ecus** [comment]
SET CSDK_HOME=C:\mycsdk , i have to put bin source???

**Comment by ifxdb** [comment]
Yes
SET CSDK_HOME=C:\mycsdk
